//! Four-layer ignore-rule stack.
//!
//! The scanner consults [`IgnoreRules`] at every major filtering step:
//!
//! 1. **Layer 1 (hard-coded):** binary content-sniff, `> max_file_size`,
//!    `.git/` contents. Always on unless [`IgnoreRulesOptions::all`] is set.
//! 2. **Layer 2 (`.gitignore`):** delegated to the [`ignore`] crate, which
//!    respects per-directory `.gitignore` files, `.git/info/exclude`, and
//!    the user's global git excludes. Disabled by
//!    [`IgnoreRulesOptions::no_gitignore`] (or by `all`).
//! 3. **Layer 3 (built-in defaults):** minified/generated/bundle/lock-file
//!    globs, vendored directories, and `@generated` /
//!    `AUTO-GENERATED` header detection in the first five lines. Disabled
//!    by `all`.
//! 4. **Layer 4 (`.dedupignore`):** per-repo ignore file with `.gitignore`
//!    syntax. Applied unconditionally — `all` does NOT disable this layer,
//!    matching the PRD.
//!
//! Precedence is **Layer 4 overrides 1–3**: if `.dedupignore` explicitly
//! whitelists a path (a `!pattern` re-include), that re-include wins over
//! a layer-3 default match. Layers 1 and 2 are independent gates — a file
//! that layer 1 drops cannot be un-dropped by layer 4, because layer 1 is
//! a physical constraint (binary, oversized, `.git/`).

use ignore::Match;
use ignore::gitignore::{Gitignore, GitignoreBuilder};
use std::path::{Path, PathBuf};
use tracing::debug;

/// Number of leading bytes content-sniffed for the binary check.
const BINARY_SNIFF_BYTES: usize = 512;
/// Number of lines inspected for the `@generated` / `AUTO-GENERATED`
/// header detection. Per the PRD.
const HEADER_SCAN_LINES: usize = 5;

/// Built-in layer-3 defaults. Combined into a single synthetic gitignore
/// so globbing benefits from the `ignore` crate's fastpath. Kept as a
/// const so unit tests can assert exact coverage.
const BUILT_IN_PATTERNS: &[&str] = &[
    // Minified / bundle / generated by filename.
    "*.min.js",
    "*.min.css",
    "*.bundle.js",
    "*.generated.*",
    // Lock files.
    "Cargo.lock",
    "package-lock.json",
    "yarn.lock",
    "poetry.lock",
    "pnpm-lock.yaml",
    // Vendored / third-party directories.
    "vendor/",
    "third_party/",
    "third-party/",
];

/// Caller-facing options for [`IgnoreRules::new`].
#[derive(Debug, Clone, Copy)]
pub struct IgnoreRulesOptions {
    /// Files strictly larger than this many bytes are skipped at layer 1.
    pub max_file_size: u64,
    /// Disable layer 2 (the gitignore stack).
    pub no_gitignore: bool,
    /// Disable layers 1–3. Layer 4 (`.dedupignore`) still applies.
    pub all: bool,
}

impl Default for IgnoreRulesOptions {
    fn default() -> Self {
        Self {
            max_file_size: 1_048_576,
            no_gitignore: false,
            all: false,
        }
    }
}

/// Compiled ignore-rule stack rooted at a single directory.
///
/// Construction walks the root once to locate and compile `.dedupignore`
/// (layer 4). `.gitignore` precedence is enforced by the [`ignore`] crate
/// at walk time via [`IgnoreRules::apply_to_walk_builder`].
pub struct IgnoreRules {
    root: PathBuf,
    opts: IgnoreRulesOptions,
    built_in: Gitignore,
    dedupignore: Option<Gitignore>,
}

impl std::fmt::Debug for IgnoreRules {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("IgnoreRules")
            .field("root", &self.root)
            .field("opts", &self.opts)
            .field("dedupignore_present", &self.dedupignore.is_some())
            .finish()
    }
}

impl IgnoreRules {
    /// Build an [`IgnoreRules`] rooted at `root`. The root is used as the
    /// base for [`Gitignore`] patterns so a `vendor/` entry in the
    /// built-in or `.dedupignore` list matches `<root>/vendor/...`.
    pub fn new(root: &Path, opts: IgnoreRulesOptions) -> Self {
        let built_in = build_built_in_gitignore(root);
        let dedupignore = build_dedupignore(root);
        Self {
            root: root.to_path_buf(),
            opts,
            built_in,
            dedupignore,
        }
    }

    /// The ignore rules the caller configured.
    pub fn options(&self) -> IgnoreRulesOptions {
        self.opts
    }

    /// Whether layer 2 (`.gitignore`) should be consulted. Honors both
    /// `no_gitignore` and `all`.
    pub fn use_gitignore_layer(&self) -> bool {
        !self.opts.no_gitignore && !self.opts.all
    }

    /// Apply every layer that the [`ignore::WalkBuilder`] knows how to
    /// enforce natively (layer 2) to `builder`. Layers 1, 3, and 4 are
    /// applied by [`IgnoreRules::is_file_ignored`] because they need
    /// per-file context (size, content, header) or deterministic
    /// precedence that the walker doesn't expose.
    pub fn apply_to_walk_builder<'a>(
        &self,
        builder: &'a mut ignore::WalkBuilder,
    ) -> &'a mut ignore::WalkBuilder {
        let use_git = self.use_gitignore_layer();
        builder
            .standard_filters(false)
            .hidden(false)
            .parents(use_git)
            .git_ignore(use_git)
            .git_exclude(use_git)
            .git_global(use_git)
            .ignore(false)
            .require_git(false);
        builder
    }

    /// Layer-1 path check: `.git/` directory contents.
    ///
    /// Returns `true` for any path whose components contain a `.git`
    /// segment (so nested `.git/` checkouts inside submodules are also
    /// skipped). Disabled when `all` is set.
    pub fn is_git_dir(&self, rel_path: &Path) -> bool {
        if self.opts.all {
            return false;
        }
        path_has_git_component(rel_path)
    }

    /// Layer-1 size check: `> max_file_size` bytes. Disabled when `all`
    /// is set.
    pub fn is_over_size_limit(&self, size: u64) -> bool {
        if self.opts.all {
            return false;
        }
        size > self.opts.max_file_size
    }

    /// Layer-1 binary content sniff on the first [`BINARY_SNIFF_BYTES`]
    /// bytes: a NUL byte marks the file as binary. Disabled when `all` is
    /// set.
    pub fn looks_binary(&self, bytes: &[u8]) -> bool {
        if self.opts.all {
            return false;
        }
        bytes.iter().take(BINARY_SNIFF_BYTES).any(|&b| b == 0)
    }

    /// Layer-3 header-scan: look at the first [`HEADER_SCAN_LINES`] lines
    /// for the case-sensitive markers `@generated` or `AUTO-GENERATED`.
    /// Disabled when `all` is set. Callers pass decoded UTF-8 text.
    pub fn has_generated_header(&self, text: &str) -> bool {
        if self.opts.all {
            return false;
        }
        text.lines()
            .take(HEADER_SCAN_LINES)
            .any(|l| l.contains("@generated") || l.contains("AUTO-GENERATED"))
    }

    /// Aggregate path-only check (layers 3 + 4). Returns `true` iff the
    /// file should be skipped based purely on its path.
    ///
    /// Precedence:
    ///
    /// - If `.dedupignore` (layer 4) explicitly whitelists via a `!pat`,
    ///   the file is **kept** even if the built-in layer matches.
    /// - Otherwise, a layer-4 ignore wins.
    /// - Otherwise (when `all` is not set), a layer-3 built-in ignore
    ///   causes a skip.
    pub fn is_path_ignored(&self, rel_path: &Path, is_dir: bool) -> bool {
        let abs = self.root.join(rel_path);

        // Layer 4 first — a whitelist in `.dedupignore` overrides layer 3.
        if let Some(d) = &self.dedupignore {
            match d.matched_path_or_any_parents(&abs, is_dir) {
                Match::Whitelist(_) => return false,
                Match::Ignore(_) => return true,
                Match::None => {}
            }
        }

        if self.opts.all {
            return false;
        }

        match self.built_in.matched_path_or_any_parents(&abs, is_dir) {
            Match::Whitelist(_) => false,
            Match::Ignore(_) => true,
            Match::None => false,
        }
    }

    /// Log a UTF-8 decode failure at `debug` level (layer 1 semantics:
    /// non-UTF-8 files skip silently). The scanner owns the decode; this
    /// helper exists so the log shape stays uniform.
    pub fn log_utf8_skip(path: &Path, err: &std::str::Utf8Error) {
        debug!(path = %path.display(), error = %err, "ignore: utf-8 decode failed, skipping");
    }
}

fn build_built_in_gitignore(root: &Path) -> Gitignore {
    let mut b = GitignoreBuilder::new(root);
    for p in BUILT_IN_PATTERNS {
        // `add_line` returns an error only on malformed globs, and all
        // entries here are static + test-covered, so `expect` is fine.
        b.add_line(None, p).expect("built-in pattern parses");
    }
    b.build().expect("built-in gitignore compiles")
}

fn build_dedupignore(root: &Path) -> Option<Gitignore> {
    let path = root.join(".dedupignore");
    if !path.exists() {
        return None;
    }
    let mut b = GitignoreBuilder::new(root);
    if let Some(err) = b.add(&path) {
        // Parse failures surface only at `debug`; the PRD treats these as
        // user-recoverable and doesn't want them derailing a scan.
        debug!(path = %path.display(), error = %err, "ignore: .dedupignore parse failed, continuing without it");
        return None;
    }
    b.build().ok()
}

/// Returns true iff any component of `p` equals `.git`.
fn path_has_git_component(p: &Path) -> bool {
    p.components().any(|c| c.as_os_str() == ".git")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    fn rules(root: &Path) -> IgnoreRules {
        IgnoreRules::new(root, IgnoreRulesOptions::default())
    }

    #[test]
    fn layer1_binary_sniff() {
        let dir = tempdir().unwrap();
        let r = rules(dir.path());
        assert!(r.looks_binary(b"hello\0world"));
        assert!(!r.looks_binary(b"hello world"));
    }

    #[test]
    fn layer1_size_cap() {
        let dir = tempdir().unwrap();
        let r = IgnoreRules::new(
            dir.path(),
            IgnoreRulesOptions {
                max_file_size: 100,
                ..Default::default()
            },
        );
        assert!(r.is_over_size_limit(101));
        assert!(!r.is_over_size_limit(100));
    }

    #[test]
    fn layer1_git_dir() {
        let dir = tempdir().unwrap();
        let r = rules(dir.path());
        assert!(r.is_git_dir(Path::new(".git/config")));
        assert!(r.is_git_dir(Path::new("sub/.git/index")));
        assert!(!r.is_git_dir(Path::new("src/main.rs")));
    }

    #[test]
    fn layer3_minified_and_lock_patterns() {
        let dir = tempdir().unwrap();
        let r = rules(dir.path());
        assert!(r.is_path_ignored(Path::new("app.min.js"), false));
        assert!(r.is_path_ignored(Path::new("dist/app.min.css"), false));
        assert!(r.is_path_ignored(Path::new("main.bundle.js"), false));
        assert!(r.is_path_ignored(Path::new("api.generated.ts"), false));
        assert!(r.is_path_ignored(Path::new("Cargo.lock"), false));
        assert!(r.is_path_ignored(Path::new("package-lock.json"), false));
        assert!(r.is_path_ignored(Path::new("yarn.lock"), false));
        assert!(r.is_path_ignored(Path::new("poetry.lock"), false));
        assert!(r.is_path_ignored(Path::new("pnpm-lock.yaml"), false));
        assert!(!r.is_path_ignored(Path::new("src/main.rs"), false));
    }

    #[test]
    fn layer3_vendored_dirs_skip_children() {
        let dir = tempdir().unwrap();
        let r = rules(dir.path());
        assert!(r.is_path_ignored(Path::new("vendor"), true));
        assert!(r.is_path_ignored(Path::new("vendor/lib.rs"), false));
        assert!(r.is_path_ignored(Path::new("third_party/a.rs"), false));
        assert!(r.is_path_ignored(Path::new("third-party/b.rs"), false));
    }

    #[test]
    fn layer3_header_generated() {
        let dir = tempdir().unwrap();
        let r = rules(dir.path());
        assert!(r.has_generated_header("// @generated\nfn f(){}"));
        assert!(r.has_generated_header("# line1\n# line2\n# AUTO-GENERATED line\n# line4"));
        // Past the 5-line window — must not match.
        assert!(!r.has_generated_header("l1\nl2\nl3\nl4\nl5\n// @generated\n"));
        assert!(!r.has_generated_header("fn real_code() {}"));
    }

    #[test]
    fn layer4_dedupignore_parses_gitignore_syntax() {
        let dir = tempdir().unwrap();
        fs::write(
            dir.path().join(".dedupignore"),
            "# comment\nsecret/\n*.tmp\n!keep.tmp\n",
        )
        .unwrap();
        let r = rules(dir.path());
        assert!(r.is_path_ignored(Path::new("secret/a.rs"), false));
        assert!(r.is_path_ignored(Path::new("scratch.tmp"), false));
        // Whitelist re-includes are honored.
        assert!(!r.is_path_ignored(Path::new("keep.tmp"), false));
    }

    #[test]
    fn layer4_whitelist_overrides_layer3() {
        // `.dedupignore` re-includes `Cargo.lock`. Layer 3 would have
        // dropped it, but layer 4's explicit whitelist must win.
        let dir = tempdir().unwrap();
        fs::write(dir.path().join(".dedupignore"), "!Cargo.lock\n").unwrap();
        let r = rules(dir.path());
        assert!(!r.is_path_ignored(Path::new("Cargo.lock"), false));
        // Unrelated layer-3 matches still drop.
        assert!(r.is_path_ignored(Path::new("app.min.js"), false));
    }

    #[test]
    fn all_flag_disables_layers_1_through_3_but_not_4() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join(".dedupignore"), "secret/\n").unwrap();
        let r = IgnoreRules::new(
            dir.path(),
            IgnoreRulesOptions {
                all: true,
                ..Default::default()
            },
        );
        // Layer 1 disabled.
        assert!(!r.looks_binary(b"\0data"));
        assert!(!r.is_over_size_limit(u64::MAX));
        assert!(!r.is_git_dir(Path::new(".git/config")));
        // Layer 3 disabled (built-in defaults don't match).
        assert!(!r.is_path_ignored(Path::new("Cargo.lock"), false));
        // Layer 4 still applies.
        assert!(r.is_path_ignored(Path::new("secret/x.rs"), false));
    }

    #[test]
    fn no_gitignore_disables_layer2_only() {
        let dir = tempdir().unwrap();
        let r = IgnoreRules::new(
            dir.path(),
            IgnoreRulesOptions {
                no_gitignore: true,
                ..Default::default()
            },
        );
        assert!(!r.use_gitignore_layer());
        // Other layers unchanged.
        assert!(r.is_path_ignored(Path::new("Cargo.lock"), false));
        assert!(r.looks_binary(b"\0x"));
    }

    #[test]
    fn built_in_pattern_coverage_is_stable() {
        // Guardrail: if a future edit reshuffles BUILT_IN_PATTERNS, at
        // least assert every named class still resolves.
        let dir = tempdir().unwrap();
        let r = rules(dir.path());
        for pat in [
            "a.min.js",
            "a.min.css",
            "a.bundle.js",
            "a.generated.rs",
            "Cargo.lock",
            "package-lock.json",
            "yarn.lock",
            "poetry.lock",
            "pnpm-lock.yaml",
        ] {
            assert!(
                r.is_path_ignored(Path::new(pat), false),
                "{pat} not matched"
            );
        }
        for d in ["vendor", "third_party", "third-party"] {
            assert!(r.is_path_ignored(Path::new(d), true), "{d} not matched");
        }
    }
}
